package cmd

import (
	"fmt"
	"io"
	"log/slog"
	"os"

	cdx "github.com/CycloneDX/cyclonedx-go"
	"github.com/spf13/cobra"

	"github.com/alejandro-velasco/bomify/internal/fsutil"
	"github.com/alejandro-velasco/bomify/internal/layout"
	"github.com/alejandro-velasco/bomify/internal/logging"
	"github.com/alejandro-velasco/bomify/internal/plugin"
	"github.com/alejandro-velasco/bomify/internal/sbom"
	"github.com/alejandro-velasco/bomify/internal/sliceutil"
	pluginlib "github.com/alejandro-velasco/bomify/pkg/plugin"
)

const sbomShort = "Compose SBOMs from deployment mediums"

func sbomCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "sbom",
		Short: sbomShort,
	}

	cmd.AddCommand(sbomComposeCmd())

	return cmd
}

const sbomComposeShort = "Compose one SBOM from several deployment mediums"

const sbomComposeLong = `Compose merges the SBOMs a composition file lists into one, for
"bomify build" to build as one package. Each source is either a medium,
whose plugin generates an SBOM from the source's options, or an existing
CycloneDX JSON file. The file's own "components" are added too.

Every medium's plugin is found before any runs. Plugins run in the
composition file's directory, so relative paths in options resolve
against it, as "sbom" paths do; each plugin checks its own options.
Each SBOM must follow the SBOM generation contract's output rules, with
no field cyclonedx-go doesn't know.

Components are merged by purl, each recording the sources it came from
in its "land.bomify.compose.sources" property; two sources disagreeing
on the same purl's type, name, version, or hashes is an error. The
result describes the composition itself, by its "name" and "version",
depending on each source's root. The same sources always compose the
same SBOM, so rebuilding it builds the same package.`

const sbomComposeExample = `  # Compose bomify.yaml and build the result
  bomify sbom compose bomify.yaml -o app.cdx.json
  bomify build app.cdx.json --tag myapp:1.4.0

  # bomify.yaml: two charts and a vendored SBOM
  name: myapp
  version: 1.4.0
  sources:
    - name: web
      medium: helm
      options:
        chart: web
        repo: oci://registry.example.com/charts
        version: 2.1.0
        values:
          - values/web.yaml
    - name: db
      medium: helm
      options:
        chart: postgresql
        repo: oci://registry-1.docker.io/bitnamicharts
        version: 15.6.0
    - name: tools
      sbom: vendor/tools.cdx.json`

func sbomComposeCmd() *cobra.Command {
	var output string

	cmd := &cobra.Command{
		Use:     "compose <file>",
		Short:   sbomComposeShort,
		Long:    sbomComposeLong,
		Example: sbomComposeExample,
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := runSBOMCompose(cmd, args[0], output, logging.FromContext(cmd.Context())); err != nil {
				return fmt.Errorf("sbom compose: %w", err)
			}
			return nil
		},
	}

	cmd.Flags().StringVarP(&output, "output", "o", "", "write the SBOM to this file instead of stdout")

	return cmd
}

func runSBOMCompose(cmd *cobra.Command, path, output string, logger *slog.Logger) error {
	c, err := sbom.LoadComposition(path)
	if err != nil {
		return err
	}

	// Before any plugin runs, so a missing one doesn't wait for the other
	// sources to generate.
	plugins, err := findSBOMPlugins(c.Sources)
	if err != nil {
		return err
	}

	parts := make([]sbom.Part, 0, len(c.Sources))
	for _, s := range c.Sources {
		bom, err := sourceSBOM(c, s, plugins[s.Medium], cmd.ErrOrStderr(), logger)
		if err != nil {
			return fmt.Errorf("source %q: %w", s.Name, err)
		}
		parts = append(parts, sbom.Part{Source: s.Name, BOM: bom})
	}

	bom, err := c.Merge(parts)
	if err != nil {
		return err
	}
	logger.Info("composed sbom", "name", c.Name, "version", c.Version, "sources", len(parts), "components", len(sliceutil.Deref(bom.Components)))

	if output == "" {
		return sbom.Write(cmd.OutOrStdout(), bom)
	}
	f, err := os.Create(output)
	if err != nil {
		return fmt.Errorf("create %s: %w", output, err)
	}
	if err := sbom.Write(f, bom); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

// findSBOMPlugins finds the SBOM generation plugin for each medium
// sources name, once however many sources share it, mapping the medium
// to the plugin's path. SourceSBOM sources need no plugin.
func findSBOMPlugins(sources []sbom.Source) (map[string]string, error) {
	plugins := map[string]string{}
	for _, s := range sources {
		if s.Type() != sbom.SourcePlugin || plugins[s.Medium] != "" {
			continue
		}
		bin, err := plugin.Find(layout.Plugins(dataDir), s.Medium, pluginlib.SBOMContract)
		if err != nil {
			return nil, fmt.Errorf("source %q: %w", s.Name, err)
		}
		plugins[s.Medium] = bin
	}
	return plugins, nil
}

// sourceSBOM returns s's SBOM: read from its file, or generated by the
// plugin at bin, which logs to logs.
func sourceSBOM(c *sbom.Composition, s sbom.Source, bin string, logs io.Writer, logger *slog.Logger) (*cdx.BOM, error) {
	if s.Type() == sbom.SourceSBOM {
		logger.Info("reading sbom", "source", s.Name, "path", s.SBOM)
		data, err := os.ReadFile(c.Path(s.SBOM))
		if err != nil {
			return nil, fmt.Errorf("read sbom: %w", err)
		}
		return sbom.DecodeStrict(data)
	}

	config, err := fsutil.WriteTemp("bomify-sbom-options-*.json", s.OptionsJSON())
	if err != nil {
		return nil, fmt.Errorf("write options file: %w", err)
	}
	defer os.Remove(config)

	logger.Info("generating sbom", "source", s.Name, "medium", s.Medium)
	return plugin.GenerateSBOM(bin, config, c.Dir(), logs)
}
