package sbom

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"

	cdx "github.com/CycloneDX/cyclonedx-go"
	"github.com/package-url/packageurl-go"
	"sigs.k8s.io/yaml"

	"github.com/alejandro-velasco/bomify/internal/sliceutil"
	pluginlib "github.com/alejandro-velasco/bomify/pkg/plugin"
)

// PropertySources is the property every component in a composed SBOM
// carries, naming the sources it came from, comma-separated and sorted.
const PropertySources = "land.bomify.compose.sources"

// extraSource is the source name components listed in the composition
// file itself are recorded under; no source can take it.
const extraSource = "components"

// composedSpecVersion is the CycloneDX version a composed SBOM is written
// in. It's pinned, so upgrading the CycloneDX library doesn't change the
// SBOM, and with it the package, of an unchanged composition.
const composedSpecVersion = cdx.SpecVersion1_6

// Composition is a composition file: a package described by several
// sources' SBOMs, merged into one by Merge.
type Composition struct {
	// Name and Version describe the composed SBOM's metadata.component.
	Name    string `json:"name"`
	Version string `json:"version"`
	// Sources are the SBOMs to merge, in order.
	Sources []Source `json:"sources"`
	// Components are packaged too, as if one more source listed them.
	Components []cdx.Component `json:"components,omitempty"`

	// dir is the composition file's directory, which Source paths and
	// generators' working directory resolve against.
	dir string
}

// Source is one SBOM a Composition merges: generated by the SBOM
// generation plugin for Medium with Options, or read from the file SBOM.
type Source struct {
	// Name identifies the source in errors and in PropertySources.
	Name    string          `json:"name"`
	Medium  string          `json:"medium,omitempty"`
	Options json.RawMessage `json:"options,omitempty"`
	SBOM    string          `json:"sbom,omitempty"`

	// typ is set by LoadComposition, once it has checked the source is
	// exactly one type.
	typ SourceType
}

// SourceType is where a Source's SBOM comes from.
type SourceType int

const (
	// SourceUnknown is a Source LoadComposition didn't load.
	SourceUnknown SourceType = iota
	// SourcePlugin is generated by the SBOM generation plugin for Medium.
	SourcePlugin
	// SourceSBOM is read from the file SBOM.
	SourceSBOM
)

// Type is where s's SBOM comes from, as LoadComposition found it.
func (s Source) Type() SourceType { return s.typ }

// LoadComposition reads the composition file at path, YAML or JSON,
// rejecting unknown keys and any source that isn't exactly one of a
// generator (medium, with options) or a file (sbom).
func LoadComposition(path string) (*Composition, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read composition: %w", err)
	}
	data, err = yaml.YAMLToJSON(data)
	if err != nil {
		return nil, fmt.Errorf("parse composition %s: %w", path, err)
	}
	var c Composition
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		return nil, fmt.Errorf("parse composition %s: %w", path, err)
	}
	if c.dir, err = filepath.Abs(filepath.Dir(path)); err != nil {
		return nil, fmt.Errorf("resolve %s: %w", path, err)
	}
	if err := c.validate(); err != nil {
		return nil, fmt.Errorf("composition %s: %w", path, err)
	}
	return &c, nil
}

func (c *Composition) validate() error {
	var errs []error
	if c.Name == "" || c.Version == "" {
		errs = append(errs, errors.New(`"name" and "version" are required`))
	}
	if len(c.Sources) == 0 && len(c.Components) == 0 {
		errs = append(errs, errors.New(`nothing to compose: no "sources" or "components"`))
	}
	seen := map[string]bool{extraSource: true}
	for i := range c.Sources {
		s := &c.Sources[i]
		where := fmt.Sprintf("sources[%d]", i)
		switch {
		case s.Name == "":
			errs = append(errs, fmt.Errorf(`%s has no "name"`, where))
		case strings.Contains(s.Name, ","):
			errs = append(errs, fmt.Errorf(`%s: name %q can't contain ","`, where, s.Name))
		case seen[s.Name]:
			errs = append(errs, fmt.Errorf(`%s: name %q is taken`, where, s.Name))
		}
		seen[s.Name] = true
		switch {
		case (s.Medium == "") == (s.SBOM == ""):
			errs = append(errs, fmt.Errorf(`%s (%s) needs exactly one of "medium" or "sbom"`, where, s.Name))
		case s.Medium != "":
			s.typ = SourcePlugin
		default:
			s.typ = SourceSBOM
		}
		if s.SBOM != "" && s.Options != nil {
			errs = append(errs, fmt.Errorf(`%s (%s): "options" only go with "medium"`, where, s.Name))
		}
	}
	return errors.Join(errs...)
}

// Dir is the composition file's directory: generators run in it, and
// relative paths in it resolve against it.
func (c *Composition) Dir() string { return c.dir }

// Path resolves path, from the composition file, against Dir.
func (c *Composition) Path(path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(c.dir, path)
}

// OptionsJSON returns s's options, "{}" if it has none.
func (s Source) OptionsJSON() []byte {
	if len(s.Options) == 0 {
		return []byte("{}")
	}
	return s.Options
}

// Part is one source's SBOM, for Merge.
type Part struct {
	Source string
	BOM    *cdx.BOM
}

// Merge merges parts, each following the SBOM generation contract's
// output rules (see pluginlib.ValidateGenerated), and the composition's
// own components into one SBOM following them too:
//
//   - metadata.component is the composition itself, name@version;
//   - components are every part's, de-duplicated by purl: the same purl
//     from two sources must agree on type, name, version and hashes, and
//     otherwise keeps the first source's fields; each records its sources
//     in PropertySources;
//   - dependencies are every part's, unioned per ref, plus the
//     composition depending on each part's root (or, when the root isn't
//     itself packaged, on each of the part's components) and on its own
//     components.
//
// Components and dependencies are sorted, so the same parts and
// components always give the same SBOM.
func (c *Composition) Merge(parts []Part) (*cdx.BOM, error) {
	purl := packageurl.NewPackageURL("generic", "", c.Name, c.Version, nil, "").String()
	root := cdx.Component{Type: cdx.ComponentTypeApplication, Name: c.Name, Version: c.Version, PackageURL: purl, BOMRef: purl}

	m := merger{components: map[string]*mergedComponent{}, deps: map[string]map[string]bool{}}
	for _, p := range parts {
		if err := pluginlib.ValidateGenerated(p.BOM); err != nil {
			return nil, fmt.Errorf("source %q: %w", p.Source, err)
		}
		components := sliceutil.Deref(p.BOM.Components)
		for _, comp := range components {
			if err := m.add(comp, p.Source); err != nil {
				return nil, err
			}
		}
		for _, d := range sliceutil.Deref(p.BOM.Dependencies) {
			m.depend(d.Ref, sliceutil.Deref(d.Dependencies)...)
		}

		partRoot := p.BOM.Metadata.Component.BOMRef
		if slices.ContainsFunc(components, func(comp cdx.Component) bool { return comp.BOMRef == partRoot }) {
			m.depend(root.BOMRef, partRoot)
			continue
		}
		// The part's root isn't packaged, so nothing in the composed SBOM
		// carries its bom-ref, and any of its own edges are dropped.
		delete(m.deps, partRoot)
		for _, comp := range components {
			m.depend(root.BOMRef, comp.BOMRef)
		}
	}
	for _, comp := range c.Components {
		if comp.BOMRef == "" {
			comp.BOMRef = comp.PackageURL
		}
		if err := m.add(comp, extraSource); err != nil {
			return nil, err
		}
		m.depend(root.BOMRef, comp.BOMRef)
	}

	bom := cdx.NewBOM()
	bom.Metadata = &cdx.Metadata{Component: &root}
	components := m.sorted()
	bom.Components = &components
	dependencies := m.dependencies()
	bom.Dependencies = &dependencies
	if err := pluginlib.ValidateGenerated(bom); err != nil {
		return nil, fmt.Errorf("composed SBOM: %w", err)
	}
	return bom, nil
}

// Write writes a composed SBOM to w as JSON, at its pinned spec version.
func Write(w io.Writer, bom *cdx.BOM) error {
	enc := cdx.NewBOMEncoder(w, cdx.BOMFileFormatJSON)
	enc.SetEscapeHTML(false)
	enc.SetPretty(true)
	if err := enc.EncodeVersion(bom, composedSpecVersion); err != nil {
		return fmt.Errorf("encode SBOM: %w", err)
	}
	return nil
}

type mergedComponent struct {
	component cdx.Component
	sources   []string
}

// merger accumulates Merge's components and dependency edges.
type merger struct {
	components map[string]*mergedComponent
	deps       map[string]map[string]bool
}

// add records comp from source, or source for a comp already added,
// failing if the two disagree on what that purl is.
func (m *merger) add(comp cdx.Component, source string) error {
	existing, ok := m.components[comp.BOMRef]
	if !ok {
		m.components[comp.BOMRef] = &mergedComponent{component: comp, sources: []string{source}}
		return nil
	}
	if diff := conflict(existing.component, comp); diff != "" {
		return fmt.Errorf("%s: sources %q and %q disagree on its %s", comp.BOMRef, existing.sources[0], source, diff)
	}
	if !slices.Contains(existing.sources, source) {
		existing.sources = append(existing.sources, source)
	}
	return nil
}

// conflict names the first field a and b, the same purl, disagree on, or
// returns "" if they don't.
func conflict(a, b cdx.Component) string {
	switch {
	case a.Type != b.Type:
		return "type"
	case a.Name != b.Name:
		return "name"
	case a.Version != b.Version:
		return "version"
	case !slices.Equal(sortedHashes(a.Hashes), sortedHashes(b.Hashes)):
		return "hashes"
	}
	return ""
}

func sortedHashes(hs *[]cdx.Hash) []cdx.Hash {
	sorted := slices.Clone(sliceutil.Deref(hs))
	slices.SortFunc(sorted, func(a, b cdx.Hash) int { return strings.Compare(string(a.Algorithm), string(b.Algorithm)) })
	return sorted
}

func (m *merger) depend(ref string, on ...string) {
	if m.deps[ref] == nil {
		m.deps[ref] = map[string]bool{}
	}
	for _, o := range on {
		m.deps[ref][o] = true
	}
}

// sorted returns the components by bom-ref, each with PropertySources.
func (m *merger) sorted() []cdx.Component {
	components := make([]cdx.Component, 0, len(m.components))
	for _, mc := range m.components {
		comp := mc.component
		sources := slices.Clone(mc.sources)
		slices.Sort(sources)
		props := slices.DeleteFunc(slices.Clone(sliceutil.Deref(comp.Properties)), func(p cdx.Property) bool { return p.Name == PropertySources })
		props = append(props, cdx.Property{Name: PropertySources, Value: strings.Join(sources, ",")})
		comp.Properties = &props
		components = append(components, comp)
	}
	slices.SortFunc(components, func(a, b cdx.Component) int { return strings.Compare(a.BOMRef, b.BOMRef) })
	return components
}

// dependencies returns the edges by ref, each ref's dependsOn sorted.
func (m *merger) dependencies() []cdx.Dependency {
	deps := make([]cdx.Dependency, 0, len(m.deps))
	for ref, on := range m.deps {
		list := make([]string, 0, len(on))
		for o := range on {
			list = append(list, o)
		}
		slices.Sort(list)
		deps = append(deps, cdx.Dependency{Ref: ref, Dependencies: &list})
	}
	slices.SortFunc(deps, func(a, b cdx.Dependency) int { return strings.Compare(a.Ref, b.Ref) })
	return deps
}
